#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"

main() {
  verifyVariables
  createFolders
  exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
}

createFolders() {
  info "Creating server folders (save, logs, backup)"
  if [[ -n "$SERVER_SAVE_DIR" ]]; then
    if [[ "$SERVER_SAVE_DIR" == /* ]]; then
      mkdir -p "$SERVER_SAVE_DIR"
    else
      mkdir -p "$install_path/$SERVER_SAVE_DIR"
    fi
  fi

  if [[ -n "$SERVER_LOG_DIR" ]]; then
    if [[ "$SERVER_LOG_DIR" == /* ]]; then
      mkdir -p "$SERVER_LOG_DIR"
    else
      mkdir -p "$install_path/$SERVER_LOG_DIR"
    fi
  fi

  if [[ -n "$BACKUP_CRON" ]] && [[ -n "$BACKUP_DIR" ]]; then
    if [[ "$BACKUP_DIR" == /* ]]; then
      mkdir -p "$BACKUP_DIR"
    else
      mkdir -p "$install_path/$BACKUP_DIR"
    fi
  fi
}

verifyVariables() {
  if [[ -n "$SERVER_SLOT_COUNT" ]]; then
    if [[ "$SERVER_SLOT_COUNT" -lt 1 ]] || [[ "$SERVER_SLOT_COUNT" -gt 16 ]]; then
      error "SERVER_SLOT_COUNT must be between 1 and 16 (actual: $SERVER_SLOT_COUNT)"
      exit 1
    fi
  fi

  if [[ -n "$SERVER_PORT" ]]; then
    warn "[DEPRECATED}: SERVER_PORT is deprecated, please use only SERVER_QUERYPORT."
    if [[ "$SERVER_PORT" -lt 1 ]] || [[ "$SERVER_PORT" -gt 65535 ]]; then
      error "SERVER_PORT must be between 1 and 65535 (actual: $SERVER_PORT)"
      exit 1
    fi
  fi

  if [[ -n "$SERVER_QUERYPORT" ]]; then
    if [[ "$SERVER_QUERYPORT" -lt 1 ]] || [[ "$SERVER_QUERYPORT" -gt 65535 ]]; then
      error "SERVER_QUERYPORT must be between 1 and 65535 (actual: $SERVER_QUERYPORT)"
      exit 1
    fi
  fi

  if [[ -n "$SERVER_IP" ]]; then
    if ! [[ "$SERVER_IP" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
      error "SERVER_IP must be a valid ipv4 address (actual: $SERVER_IP)"
      exit 1
    fi
  fi

  if [[ -n "$STEAM_API_PUBLIC_IP" ]]; then
    if ! [[ "$STEAM_API_PUBLIC_IP" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
      error "STEAM_API_PUBLIC_IP must be a valid ipv4 address (actual: $STEAM_API_PUBLIC_IP)"
      exit 1
    fi
  fi

  if [[ -n "$UPDATE_CHECK_PLAYERS" ]]; then
    if [[ "$UPDATE_CHECK_PLAYERS" != "true" ]] && [[ "$UPDATE_CHECK_PLAYERS" != "false" ]]; then
      error "UPDATE_CHECK_PLAYERS must be true or false (actual: $UPDATE_CHECK_PLAYERS)"
      exit 1
    fi
  fi
}

main
